// Generated by CoffeeScript 1.8.0

/*
    This class handles the caption tracks for the video player.
    It supports currently only one (english) caption track.

    Possible improvements:
    - support mutliple caption tracks (different languages)
    - setCaptionsVisibility() should get an additional parameter which track should be enabled
 */
window.Html5Player || (window.Html5Player = {});

window.Html5Player.Captions = (function() {
  function Captions(player, $baseElement) {
    this.player = player;
  }

  Captions.prototype.updateCaptions = function(captionsUrl) {
    this.removeCaptions();
    return this.addCaptions(captionsUrl);
  };

  Captions.prototype.removeCaptions = function() {
    return $(this.player.videoA).find('track').remove();
  };

  Captions.prototype.addCaptions = function(captionsUrl) {
    $(this.player.videoA).append($('<track label="English" kind="captions" srclang="en" src="' + captionsUrl + '" default>'));
    return this.player.videoA.textTracks[0].mode = 'hidden';
  };

  Captions.prototype.setCaptionsVisibility = function(visibility) {
    return this.player.videoA.textTracks[0].mode = visibility;
  };

  return Captions;

})();

//# sourceMappingURL=captions.js.js.map
