// Generated by CoffeeScript 1.8.0

/*
    This class handles all the actions and events for cue points of clicked tags.
    When one clicks on a cue point, the player will jump to the according position.
 */
window.Html5Player || (window.Html5Player = {});

window.Html5Player.CuePoints = (function() {
  function CuePoints(player, $baseElement) {
    this.player = player;
    this.$seeker = $baseElement.find('.progress');
  }

  CuePoints.prototype.updateCuePoints = function(cuePoints) {
    this.removeCuePoints();
    return this.showCuePoints(cuePoints);
  };

  CuePoints.prototype.showCuePoints = function(cuePoints) {
    var cuePoint, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = cuePoints.length; _i < _len; _i++) {
      cuePoint = cuePoints[_i];
      _results.push(this.addCuePoint(cuePoint));
    }
    return _results;
  };

  CuePoints.prototype.removeCuePoints = function() {
    return this.$seeker.find('.cuePoint').remove();
  };

  CuePoints.prototype.addCuePoint = function(cuePointTime) {
    var cuePoint, diff, offset;
    offset = Math.ceil((cuePointTime / this.player.videoA.duration) * 100);
    diff = Math.ceil((7 / this.$seeker.width()) * 100);
    offset -= diff;
    cuePoint = $('<div class="cuePoint" data-seconds=' + cuePointTime + ' style="left:' + offset + '%;"></div>').prependTo(this.$seeker);
    return cuePoint.on('click', (function(_this) {
      return function(event) {
        event.preventDefault();
        event.stopPropagation();
        return _this.player.gototime(cuePointTime);
      };
    })(this));
  };

  return CuePoints;

})();

//# sourceMappingURL=cuepoints.js.js.map
