// Generated by CoffeeScript 1.8.0

/*
    This class handles all the actions and events for a custom video preview.
    This is used for tagged comments.
 */
window.Html5Player || (window.Html5Player = {});

window.Html5Player.CustomPreview = (function() {
  function CustomPreview(player, $baseElement) {
    this.player = player;
    this.$seeker = $baseElement.find('.progress');
    this.startTime = -1;
    this.endTime = -1;
  }

  CustomPreview.prototype.show = function(startTime, endTime) {
    this.startTime = startTime;
    this.endTime = endTime;
    if (this.player.hasPreview) {
      this.player.preview.stop();
    }
    this.player.customPreviewIsShown = true;
    this.addPreviewRange(startTime, endTime);
    return this.start();
  };

  CustomPreview.prototype.addPreviewRange = function(startTime, endTime) {
    var offset, width;
    offset = (startTime / this.player.videoA.duration) * 100;
    width = ((endTime - startTime) / this.player.videoA.duration) * 100;
    return this.$seeker.prepend($('<div class="previewRange" style="left:' + offset + '%; width:' + width + '%;"></div>'));
  };

  CustomPreview.prototype.stop = function() {
    this.$seeker.find('.previewRange').remove();
    this.player.pause();
    return this.player.customPreviewIsShown = false;
  };

  CustomPreview.prototype.update = function() {
    if (this.player.currentTime() > this.endTime) {
      return this.stop();
    }
  };

  CustomPreview.prototype.start = function() {
    this.player.gototime(this.startTime);
    return this.player.play;
  };

  CustomPreview.prototype.seekTimeInPreviewRange = function(time) {
    if ((this.startTime <= time && time <= this.endTime)) {
      return true;
    }
    return false;
  };

  return CustomPreview;

})();

//# sourceMappingURL=custom_preview.js.js.map
