// Generated by CoffeeScript 1.8.0

/*
    This class handles the loading overlay for the video.
      It offers the action to play or preview a video.
 */
window.Html5Player || (window.Html5Player = {});

window.Html5Player.LoadingOverlay = (function() {
  function LoadingOverlay(player, $baseElement) {
    this.player = player;
    this.$overlay = $baseElement.find('.loadingOverlay');
    $(window).on("videosReady", (function(_this) {
      return function() {
        return _this.showActions();
      };
    })(this));
    this.$overlay.on("click", ".icon-play", (function(_this) {
      return function() {
        _this.player.controls.$playButton.click();
        return _this.$overlay.hide();
      };
    })(this));
    this.$overlay.on("click", ".icon-preview", (function(_this) {
      return function() {
        _this.player.controls.$previewButton.click();
        return _this.$overlay.hide();
      };
    })(this));
  }

  LoadingOverlay.prototype.showActions = function() {
    if (this.player.hasPreview) {
      return this.$overlay.html("<i class=\"xikolo-icon icon-play\" style=\"\n  line-height: 5rem;\n  padding-right: 1rem;\n  cursor: pointer;\"></i>\n<i class=\"xikolo-icon icon-preview\" style=\"\n  vertical-align: 0;\n  line-height: 5rem;\n  font-size: 4rem;\n  padding-left: 1rem;\n  margin-right: 0;\n  cursor: pointer;\"></i>");
    } else {
      return this.$overlay.html("<i class=\"xikolo-icon icon-play\" style=\"\n  line-height: 5rem;\n  padding-right: 1rem;\n  cursor: pointer;\"></i>");
    }
  };

  LoadingOverlay.prototype.hidePreviewAction = function() {
    return this.$overlay.find('.icon-preview').hide();
  };

  LoadingOverlay.prototype.showPreviewAction = function() {
    return this.$overlay.find('.icon-preview').show();
  };

  return LoadingOverlay;

})();

//# sourceMappingURL=loading_overlay.js.js.map
