// Generated by CoffeeScript 1.8.0

/*
    This class handles the overlay for the most watched sections of a video.
    THe overlay consists of ranged in the timeline.
 */
window.Html5Player || (window.Html5Player = {});

window.Html5Player.MostWatched = (function() {
  function MostWatched(player, $baseElement) {
    this.player = player;
    this.$seeker = $baseElement.find('.progress');
  }

  MostWatched.prototype.updateMostWatched = function(mostWatchedSections) {
    this.removeMostWatched();
    return this.showMostWatched(mostWatchedSections);
  };

  MostWatched.prototype.showMostWatched = function(mostWatchedSections) {
    var section, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = mostWatchedSections.length; _i < _len; _i++) {
      section = mostWatchedSections[_i];
      _results.push(this.addMostWatched (section));
    }
    return _results;
  };

  MostWatched.prototype.removeMostWatched = function() {
    return this.$seeker.find('.mostWatched').remove();
  };

  MostWatched.prototype.addMostWatched = function(section) {
    var offset, width;
    offset = Math.ceil((section.start / this.player.videoA.duration) * 100);
    width = Math.ceil(((section.end - section.start) / this.player.videoA.duration) * 100);
    return this.$seeker.prepend($('<div class="mostWatched" style="left:' + offset + '%; width:' + width + '%; display:none;"></div>'));
  };

  return MostWatched;

})();

//# sourceMappingURL=most_watched.js.js.map
